Repository digiaonline/graphql-php, pull requests merged in 2018-07, with the labels that each got.

#248 Rename phpunit.xml to phpunit.xml.dist and ignore the former
  .gitignore
  phpunit.xml.dist
Labels: dev environment

#250 Replace symfony/polyfill-mbstring with a hard ext-mbstring requirement
  .idea/graphql-php.iml
  .idea/php.xml
  README.md
  composer.json
Labels: dev environment, documentation, enhancement, preformance, public api

#251 Bump phpstan analysis level to 3
  composer.json
  src/Error/GraphQLException.php
  src/Schema/Building/BuildInfo.php
  src/Schema/Extension/ExtensionContext.php
  src/Schema/Schema.php
  src/Schema/Validation/SchemaValidator.php
  src/Schema/Validation/ValidationContext.php
  src/Schema/Validation/ValidationContextInterface.php
  src/Type/Definition/CompositeTypeInterface.php
  src/Type/Definition/InputTypeInterface.php
  src/Type/Definition/LeafTypeInterface.php
  src/Type/Definition/OutputTypeInterface.php
  src/Type/Definition/SerializableTypeInterface.php
  src/Util/TypeInfo.php
  src/Validation/Rule/UniqueArgumentNamesRule.php
  src/Validation/Rule/UniqueFragmentNamesRule.php
  src/Validation/Rule/UniqueInputFieldNamesRule.php
  src/Validation/Rule/UniqueOperationNamesRule.php
  src/Validation/Rule/UniqueVariableNamesRule.php
Labels: enhancement, tests

#252 Bump the phpstan analysis level to 4
  composer.json
  src/Execution/Execution.php
  src/Execution/Executor.php
  src/Execution/ValuesHelper.php
  src/Language/Lexer.php
  src/Language/NodePrinter.php
  src/Schema/Validation/Rule/DirectivesRule.php
  src/Schema/Validation/Rule/TypesRule.php
  src/Type/Coercer/IntCoercer.php
  src/Type/Definition/ObjectType.php
  src/Type/Definition/ScalarType.php
  src/Type/Definition/SerializableTypeInterface.php
  src/Type/IntrospectionProvider.php
  src/Util/ValueConverter.php
  src/Validation/ValidationContext.php
  src/Validation/Validator.php
  tests/Functional/Type/SerializationTest.php
  tests/Unit/Type/Coercer/IntCoercerTest.php
  tests/Unit/Util/ValueConverterTest.php
Labels: bug, preformance, refactor

#254 Fix two lexer issues
  src/Language/Lexer.php
  tests/Functional/Language/ParserTest.php
  tests/Unit/Language/LexerTest.php
Labels: bug, tests

#256 Refactor invariant() usage somewhat
  src/Error/helpers.php
  src/Language/Source.php
  src/Schema/DefinitionBuilder.php
  src/Schema/Extension/ExtensionContext.php
  src/Schema/Schema.php
  src/Type/Definition/ArgumentsTrait.php
  src/Type/Definition/EnumType.php
  src/Type/Definition/FieldsTrait.php
  src/Type/Definition/InputObjectType.php
  src/Type/Definition/InterfaceType.php
  src/Type/Definition/ObjectType.php
  src/Type/Definition/UnionType.php
  src/Type/definition.php
  tests/Functional/Type/PredicateTest.php
Labels: typesystem, utility

#262 Fixes bug with scalar name introspection
  src/Execution/Executor.php
  tests/Functional/IntrospectionTest.php
Labels: bug
