Repository digiaonline/graphql-php, pull requests merged in 2018-08, with the labels that each got.

#259 Add unit tests and improved phpdoc for ValueHelper, refactor some helpers to be static
  composer.json
  src/Execution/FieldCollector.php
  src/Execution/ValuesHelper.php
  src/GraphQL.php
  src/Language/Visitor/TypeInfoVisitor.php
  src/Schema/DefinitionBuilder.php
  src/Schema/DefinitionPrinter.php
  src/Schema/Validation/Rule/DirectivesRule.php
  src/Schema/Validation/Rule/TypesRule.php
  src/Util/NameHelper.php
  src/Util/TypeASTConverter.php
  src/Util/TypeHelper.php
  src/Util/UtilityProvider.php
  src/Util/ValueASTConverter.php
  src/Util/ValueConverter.php
  src/Util/ValueHelper.php
  src/Util/helpers.php
  src/Validation/Conflict/ConflictFinder.php
  src/Validation/Rule/FragmentsOnCompositeTypesRule.php
  src/Validation/Rule/PossibleFragmentSpreadsRule.php
  src/Validation/Rule/VariablesAreInputTypesRule.php
  src/Validation/Rule/VariablesInAllowedPositionRule.php
  src/Validation/comparators.php
  tests/Unit/Util/NameHelperTest.php
  tests/Unit/Util/ValueHelperTest.php
Labels: performance, refactor, tests, utility

#266 Add some intermediate variables so type-hint information isn't lost
  src/GraphQL.php
Labels: enhancement

#265 Readme draft
  .gitignore
  README.md
Labels: documentation

#268 Do not use dev-master
  README.md
Labels: documentation

#269 README (alpha)
  README.md
Labels: documentation

#271 NodeBuilder tests
  tests/Unit/Language/NodeBuilderTest.php
Labels: tests

#273 Named type node interface
  src/Language/Node/EnumTypeDefinitionNode.php
  src/Language/Node/InputObjectTypeDefinitionNode.php
  src/Language/Node/InterfaceTypeDefinitionNode.php
  src/Language/Node/NamedTypeNode.php
  src/Language/Node/NamedTypeNodeInterface.php
  src/Language/Node/ObjectTypeDefinitionNode.php
  src/Language/Node/ScalarTypeDefinitionNode.php
  src/Language/Node/TypeNodeInterface.php
  src/Language/Node/TypeSystemDefinitionNodeInterface.php
  src/Language/Node/UnionTypeDefinitionNode.php
  src/Schema/Building/BuildingContext.php
  src/Schema/DefinitionBuilder.php
  src/Schema/DefinitionBuilderInterface.php
Labels: code quality, refactor

#267 Add a SourceBuilderInterface along with two basic implementations
  README.md
  src/Error/FileNotFoundException.php
  src/Language/FileSourceBuilder.php
  src/Language/MultiFileSourceBuilder.php
  src/Language/SourceBuilderInterface.php
  tests/Functional/Language/FileSourceBuilderTest.php
  tests/Functional/Language/MultiFileSourceBuilderTest.php
Labels: SDL, documentation, enhancement, public api

#275 Remove visitor trait
  src/Language/Node/AbstractNode.php
  src/Language/Node/EnumTypeDefinitionNode.php
  src/Language/Node/EnumTypeExtensionNode.php
  src/Language/Node/EnumValueDefinitionNode.php
  src/Language/Node/FieldDefinitionNode.php
  src/Language/Node/FieldNode.php
  src/Language/Node/FragmentDefinitionNode.php
  src/Language/Node/FragmentSpreadNode.php
  src/Language/Node/InlineFragmentNode.php
  src/Language/Node/InputObjectTypeDefinitionNode.php
  src/Language/Node/InputObjectTypeExtensionNode.php
  src/Language/Node/InputValueDefinitionNode.php
  src/Language/Node/InterfaceTypeDefinitionNode.php
  src/Language/Node/InterfaceTypeExtensionNode.php
  src/Language/Node/NameTrait.php
  src/Language/Node/NodeInterface.php
  src/Language/Node/ObjectTypeDefinitionNode.php
  src/Language/Node/ObjectTypeExtensionNode.php
  src/Language/Node/OperationDefinitionNode.php
  src/Language/Node/ScalarTypeDefinitionNode.php
  src/Language/Node/ScalarTypeExtensionNode.php
  src/Language/Node/UnionTypeDefinitionNode.php
  src/Language/Node/UnionTypeExtensionNode.php
  src/Language/Node/VariableDefinitionsAwareInterface.php
  src/Language/Visitor/AcceptsVisitorsInterface.php
  src/Language/Visitor/AcceptsVisitorsTrait.php
  src/Validation/Rule/KnownDirectivesRule.php
  src/Validation/ValidationContext.php
  src/Validation/ValidationContextInterface.php
Labels: language, refactor
